FROM maven:3.9-amazoncorretto-24-alpine AS build
COPY src /usr/src/app/src
COPY pom.xml /usr/src/app
ENV vertx.disableDnsResolver=true
ENV java.net.preferIPv4Stack=true
RUN mvn -DskipTests -f /usr/src/app/pom.xml clean package -e

FROM eclipse-temurin:24.0.2_12-jre-ubi10-minimal
COPY --from=build /usr/src/app/target/Signal-0.0.1-SNAPSHOT.jar /usr/app/Signal-0.0.1-SNAPSHOT.jar
EXPOSE 8084
ENTRYPOINT ["java", "-jar","/usr/app/Signal-0.0.1-SNAPSHOT.jar"]
