spring.application.name=Signal
spring.docker.compose.enabled=false
halo.url=${HALO_URL}
polvo.url=${POLVO_URL}
nectar.url=${NECTAR_URL}
server.port=${SIGNALAPI_PORT}
jwt.secret=${JWT_SECRET}
postgres.db=${POSTGRES_DB_SIGNALAPI}
postgres.user=${POSTGRES_USER_SIGNALAPI}
postgres.port=${POSTGRES_PORT_SIGNALAPI}
postgres.password=${POSTGRES_PASSWORD_SIGNALAPI}
postgres.host=${POSTGRES_HOST_SIGNALAPI}
# Write to a specific file relative to the project directory
logging.file.name=logs/application.log

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST_SIGNALAPI}:${POSTGRES_PORT_SIGNALAPI}/${POSTGRES_DB_SIGNALAPI}
spring.datasource.username=${POSTGRES_USER_SIGNALAPI}
spring.datasource.password=${POSTGRES_PASSWORD_SIGNALAPI}




